export default { //JSONファイルとしてでなくJSのオブジェクトとしてエクスポートする
    "A1":[//パート
        {
            "textId":0,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"相変わらず目覚めは最悪で、$今ここで微睡んでいる事すら後悔してしまうほどだった。$もう一度眠りにつこう。$そう思ってベッドに潜ってみたものの、あれだけ寝ていたのだ。当然、眠れる訳がなかった。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":1,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"ずっと太陽から逃げ続けていた僕にとっては、寝ているのも起きているのも変わらない。$強いて言うならそこに意識があるか否か。$それだけが違っている。$いや、本当はそれすらも変わらないのかもしれない。$なぜなら僕は、$ずっと。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":2,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"いつからここに居るのだろう。$いつまでここに居られるのだろう。$そんな事すら分からないほど途方もない時間をこの空間の中で過ごした。$変わり映えのない日常。$それを変える事のできない自分。$僕は何もかもを好きになれなかった。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":3,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"いっそ*カタストロフィ*が全てを壊してしまうなら、それもいいかもしれない。$すべて跡形も無くなってしまったら僕と、彼女の抱える*罪*も消えるだろうか。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":4,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"",
                "text":"(ドアが開く音)",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":5,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「ただいま。…ってまた寝たふりしてる。$どうせバレるんだからそれ、やめてくれない？」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":6,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"声のする方を見やると、そこにはいつにも増して疲れ切った表情のニアが立っていた。$蔑むような凍てつく視線が嫌で、僕は彼女から目を背ける。$静寂が、やけに鮮明に聞こえた。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":7,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「…ったく、こっち向けっての！もう！」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":8,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"彼女は勢いよく僕の殻を剥いだ。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":9,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「こんな暗い部屋で寝っ転がってるからそんな性格になったんじゃない？せめてカーテンくらい開けなさいよ！」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":10,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"ニアが何の躊躇いもなくカーテンを開けると、部屋いっぱいに懐かしい光が差し込んできた。僕がその眩しさに目を細めていると、彼女は大きなため息をついた。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":11,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「…ったく、久々に顔見にきてやったのに、何か変わってるかと思ったら全然変わってない。タウってば、成長ってものを知らないの？本当あなたって人は…」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":12,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「で、何しに来たの？」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":13,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"面倒くさかったので続きを遮るようにして、言った。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":14,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「今日が、最後だから。ちょっとタウの顔が見たかっただけ」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":15,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「…」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":16,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「タウも知ってるでしょ？カタストロフィ。あれ、また始まるみたいだから。私、Wood にずっと居なくちゃいけないんだよね。もう帰る暇も無いっていうか。だから…」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":17,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「Wood?何それ。そんな話、一度も聞いた事なかった。」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":18,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「カタストロフィに対抗する、唯一の組織。対抗する…って言っても、どうにもならないんだろうけど」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":19,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「だったら…。だったら、ずっとここに居ればいいじゃないか！幸い、僕らイデアは何も食べなくても生きていける。なのになぜ、危険を冒してまでそんな事を…」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":20,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「戦わなくちゃいけない理由が出来たから。今度は誰かの意思じゃない。私自身の意思で戦ってる」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":21,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「別にニアじゃなくたっていいのに。大体、これまで散々戦って傷ついてきたのに、これ以上ニアが傷つく必要なんてないよ！」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":22,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「でも、誰かがやらなきゃいけない。これは人間の力だけではどうにもならない事なの。タウならよく知ってるでしょ？私達イデアだけしか、アレを操る事ができない。もちろん普通の兵器だってあるにはあったんだけど…」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":23,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"",
                "text":"その言葉の続きを、僕は察する事ができた。嫌というほど聞こえていた騒音の類は、いつしか鳴りを潜めていた。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":24,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「そういえば、預かってきたものがあるんだった。はいこれ。一応、上からの命令だから」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":25,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"",
                "text":"ニアから差し出されたのは、色のついた封筒だった。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":26,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「…何これ」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":27,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「招待状。三島司令から預かってきたの。どうせ寝っ転がってるだけで何もしないんだったら、ちょっとは人様のお役に立ったらどう？」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":28,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「三島司令って、あの三島司令？」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":29,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「そう、あの三島司令。今は Wood の司令官やってるけど」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":30,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"",
                "text":"三島トウジ。彼は戦後唯一僕らイデアを擁護した人物だった。もっとも、僕らを戦争に駆り出したのは他でもない、彼だったのだけど。",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":31,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「今更何を…。まさか、また戦えなんていうつもりじゃないよね？」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":32,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「そう。そのまさか。三島司令がいうには、最終作戦のための人員が足りないんだって。それも、あと 1 人」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":33,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「よりによって、なんで僕が…」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":34,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「さぁ？よっぽど人員が足りないんじゃない？まさに猫の手も借りたいってやつ。もっとも、今のタウを見てると猫の方がよっぽどマシに見えるけど」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":35,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「そんな言い方ないだろ！？」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":36,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「だって、事実じゃない。どうせ今のタウには戦う度胸なんてどこにもないもんね。…ったく、よりによってなんでこいつなんだか」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":37,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「久しぶりに帰って来たと思ったら嫌味ばっかり。もう帰ってよ。せめて残り少ない明日を、有意義に過ごしたいからさ」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":38,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「何その言い方。イラッとするんだけど」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":39,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「今まで散々言いたい放題言われてきたんだから、ちょっとくらいいいだろ？」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":40,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「私だって言いたくて言ってるんじゃないよ！私だって最初の頃はタウと一緒に過ごせて幸せだったよ？でもそれ以上に我慢しなきゃいけない事が多くなって、好きでいる時間より嫌いでいる時間の方が長くなっちゃって…。正直、どうすればいいのかわからないよ」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
        {
            "textId":41,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「だったら、好きにすればいいだろ！大体いつもいつもここに来る事自体、鬱陶しいんだよ！そもそも僕はニアと一緒に居たいだなんて一度も言った事もない。そっちが勝手に付きまとってるだけだ。僕はこんな事望んでない」",
                "effect":{

                }
            },
            "backgroundImage":"city01.jpeg"
        },
    ]
}
