export default { //JSONファイルとしてでなくJSのオブジェクトとしてエクスポートする
    "A1":[//パート
        {
            "textId":0,
            // "type":"normal",
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"キャラ１",
                "text":"今日の*/ご飯/*は",
                "effect":{

                }
            }
        },
        {
            "textId":1,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"キャラ１",
                "text":"焼肉に行こうと思ったが/お金/がなかったので、*自炊*することにした。",
                "effect":{
                    
                }
            }
        },
        {
            "textId":2,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"キャラ２",
                "text":"冷蔵庫を見た。",
                "effect":{
                    
                }
            }
        },
        {
            "textId":3,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"キャラ２",
                "text":"何も食べれそうなものがなかった。あったのは調味料とビールだけ…。",
                "effect":{
                    
                }
            }
        },
        {
            "textId":4,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"キャラ２",
                "text":"「こりゃ、ダメだな...笑」",
                "effect":{
                    
                }
            }
        },
        {
            "textId":5,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"キャラ２",
                "text":"俺はそうつぶやいて、近所の/スーパー/へ出かけること決意した。",
                "effect":{
                    
                }
            }
        },
        {
            "textId":6,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"キャラ２",
                "text":"顔を洗い、髭を剃り、歯を磨いて、…。それから着替え、身支度を済ませてドアを開けた。",
                "effect":{
                    
                }
            }
        }
    ]
}