export default { //JSONファイルとしてでなくJSのオブジェクトとしてエクスポートする
    "A1":[//パート
        {
            "textId":0,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"相変わらず目覚めは最悪で、今ここで微睡んでいる事すら後悔してしまうほどだった。もう一度眠りにつこう。そう思ってベッドに潜ってみたものの、あれだけ寝ていたのだ。当然、眠れる訳がなかった。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":1,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"ずっと太陽から逃げ続けていた僕にとっては、寝ているのも起きているのも変わらない。強いて言うならそこに意識があるか否か。それだけが違っている。いや、本当はそれすらも変わらないのかもしれない。なぜなら僕は、ずっと。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":2,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"いつからここに居るのだろう。いつまでここに居られるのだろう。そんな事すら分からないほど途方もない時間をこの空間の中で過ごした。変わり映えのない日常。それを変える事のできない自分。僕は何もかもを好きになれなかった。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city02.jpeg"
        },
        {
            "textId":3,
            "onePicture":true,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"いっそカタストロフィが全てを壊してしまうなら、それもいいかもしれない。すべて跡形も無くなってしまったら僕と、彼女の抱える罪も消えるだろうか。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/map.png"
        },
        {
            "textId":4,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"キャラ(右)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"(ドアが開く音)",
                "effect":{

                }
            },
            "backgroundImage":"images/background/map.png"
        },
        {
            "textId":5,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「ただいま。…ってまた寝たふりしてる。どうせバレるんだからそれ、やめてくれない？」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/concept.png"
        },
        {
            "textId":6,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"声のする方を見やると、そこにはいつにも増して疲れ切った表情のニアが立っていた。蔑むような凍てつく視線が嫌で、僕は彼女から目を背ける。静寂が、やけに鮮明に聞こえた。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/concept.png"
        },
        {
            "textId":7,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「…ったく、こっち向けっての！もう！」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/concept.png"
        },
        {
            "textId":8,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"彼女は勢いよく僕の殻を剥いだ。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":9,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「こんな暗い部屋で寝っ転がってるからそんな性格になったんじゃない？せめてカーテンくらい開けなさいよ！」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":10,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"ニアが何の躊躇いもなくカーテンを開けると、部屋いっぱいに懐かしい光が差し込んできた。僕がその眩しさに目を細めていると、彼女は大きなため息をついた。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":11,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「…ったく、久々に顔見にきてやったのに、何か変わってるかと思ったら全然変わってない。タウってば、成長ってものを知らないの？本当あなたって人は…」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":12,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「で、何しに来たの？」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":13,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"面倒くさかったので続きを遮るようにして、言った。",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":14,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「今日が、最後だから。ちょっとタウの顔が見たかっただけ」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":15,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「…」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":16,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「タウも知ってるでしょ？カタストロフィ。あれ、また始まるみたいだから。私、Wood にずっと居なくちゃいけないんだよね。もう帰る暇も無いっていうか。だから…」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":17,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"タウ",
                "text":"「Wood?何それ。そんな話、一度も聞いた事なかった。」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
        {
            "textId":18,
            "onePicture":false,
            "characterList":{//各キャラの設定
                "left":{//左
                    "name":"キャラ(左)",
                    "src":"images/character/bengal.png",
                    "status":{
                        "brightnessDown":true//明度(true)の時は落とす
                    }
                },
                "center":{//中央
                    "name":"キャラ(中)",
                    "src":"images/character/transparent_background.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                },
                "right":{//右
                    "name":"ニア",
                    "src":"images/character/bibian.png",
                    "status":{
                        "brightnessDown":false//明度(true)の時は落とす
                    }
                }
            },
            "characterText":{
                "name":"ニア",
                "text":"「カタストロフィに対抗する、唯一の組織。対抗する…って言っても、どうにもならないんだろうけど」",
                "effect":{

                }
            },
            "backgroundImage":"images/background/city01.jpeg"
        },
    ]
}
